// flow-typed signature: 9382309a982b831a1013046fc7fb165f
// flow-typed version: <<STUB>>/remove-lockfiles_v^1.1.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-lockfiles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-lockfiles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remove-lockfiles/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remove-lockfiles/cli.js' {
  declare module.exports: $Exports<'remove-lockfiles/cli'>;
}
declare module 'remove-lockfiles/index' {
  declare module.exports: $Exports<'remove-lockfiles'>;
}
declare module 'remove-lockfiles/index.js' {
  declare module.exports: $Exports<'remove-lockfiles'>;
}
